version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies"
      - npm install
  build:
    commands:
      - echo "Building the application"
      - npm run build
  post_build:
    commands:
      - echo "build completed on $(date)"
      - mkdir -p deploy
      - cp -r * deploy/
      #- cp appsec.yaml deploy/
      - cp -r scripts/ deploy/scripts/
artifacts:
  files:
    - deploy/**/*
  discard-paths: no
